/**
 * 2016/9/27 19:46:15 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.commodity.dao;

import com.dyb.platforms.fixfunds.services.business.commodity.entity.Commodity;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 商品信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/27.
 */
public interface ICommodityDao extends IIbatisDataDAO<Commodity, String> {

}
