/**
 * 2016/10/14 17:22:20 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.donationreceiptapply.entity;

import com.dyb.platforms.fixfunds.services.business.donationreceiptapply.entity.em.ApplyStatus;

import java.util.Date;

/**
 * 收据申请
 * Created by lenovo on 2016/10/14.
 */
public class DonationReceiptApply implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -2821480614515710464L;

    // 收据申请单编号 [主键]
    private String donationReceiptApplyCode;
    // 收件人地址
    private String address;
    // 收件人号码
    private String phone;
    // 收件人
    private String receiver;
    // 是否含捐赠证书
    private Boolean isCertificate;
    // 收据金额
    private Double receiptMoney;
    // 收取方式
    private String chargeWay;
    // 状态
    private ApplyStatus applyStatus;
    // 申请时间
    private Date applyTime;
    // 捐赠人code
    private String accountCode;

    /** 
     * 获取收据申请单编号 [主键]
     * 
     * @return 收据申请单编号
     */
    public String getDonationReceiptApplyCode() {
        return donationReceiptApplyCode;
    }

    /** 
     * 设置收据申请单编号 [主键]
     * 
     * @param donationReceiptApplyCode 收据申请单编号
     */
    public void setDonationReceiptApplyCode(String donationReceiptApplyCode) {
        this.donationReceiptApplyCode = donationReceiptApplyCode;
    }

    /** 
     * 获取收件人地址
     * 
     * @return 收件人地址
     */
    public String getAddress() {
        return address;
    }

    /** 
     * 设置收件人地址
     * 
     * @param address 收件人地址
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /** 
     * 获取收件人号码
     * 
     * @return 收件人号码
     */
    public String getPhone() {
        return phone;
    }

    /** 
     * 设置收件人号码
     * 
     * @param phone 收件人号码
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** 
     * 获取收件人
     * 
     * @return 收件人
     */
    public String getReceiver() {
        return receiver;
    }

    /** 
     * 设置收件人
     * 
     * @param receiver 收件人
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /** 
     * 获取是否含捐赠证书
     * 
     * @return 是否含捐赠证书
     */
    public Boolean isIsCertificate() {
        return isCertificate;
    }

    /** 
     * 设置是否含捐赠证书
     * 
     * @param isCertificate 是否含捐赠证书
     */
    public void setIsCertificate(Boolean isCertificate) {
        this.isCertificate = isCertificate;
    }

    /** 
     * 获取收据金额
     * 
     * @return 收据金额
     */
    public Double getReceiptMoney() {
        return receiptMoney;
    }

    /** 
     * 设置收据金额
     * 
     * @param receiptMoney 收据金额
     */
    public void setReceiptMoney(Double receiptMoney) {
        this.receiptMoney = receiptMoney;
    }

    /** 
     * 获取收取方式
     * 
     * @return 收取方式
     */
    public String getChargeWay() {
        return chargeWay;
    }

    /** 
     * 设置收取方式
     * 
     * @param chargeWay 收取方式
     */
    public void setChargeWay(String chargeWay) {
        this.chargeWay = chargeWay;
    }

    /** 
     * 获取状态
     * 
     * @return 状态
     */
    public ApplyStatus getApplyStatus() {
        return applyStatus;
    }

    /** 
     * 设置状态
     * 
     * @param applyStatus 状态
     */
    public void setApplyStatus(ApplyStatus applyStatus) {
        this.applyStatus = applyStatus;
    }

    /** 
     * 获取申请时间
     * 
     * @return 申请时间
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /** 
     * 设置申请时间
     * 
     * @param applyTime 申请时间
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /** 
     * 获取捐赠人code
     * 
     * @return 捐赠人code
     */
    public String getAccountCode() {
        return accountCode;
    }

    /** 
     * 设置捐赠人code
     * 
     * @param accountCode 捐赠人code
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

}
