/**
 * 2016/10/10 10:42:00 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.messengerbean.dao;

import com.dyb.platforms.fixfunds.services.business.messengerbean.entity.MessengerBean;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 信使豆信息 Ibatis Dao 接口
 * Created by lenovo on 2016/10/10.
 */
public interface IMessengerBeanDao extends IIbatisDataDAO<MessengerBean, String> {

}
