/**
 * 2016/9/26 9:20:02 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.merchant.entity;

import com.dyb.platforms.fixfunds.services.business.merchant.entity.em.*;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 商家信息
 * Created by lenovo on 2016/09/26.
 */
public class Merchant implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -1297503756963416832L;

    // 商家Code [主键]
    private String merchantCode;
    // 商家名称
    private String merchantName;
    // 激励模式
    private Integer incentiveMode;
    // 店铺名称
    private String shopName;
    // 商家类型
    private MerchantType merchantType;
    // 营业开始时间
    private String businessStartTime;
    // 营业结束时间
    private String businessEndTime;
    // 商家地址
    private String merchantAddress;
    // 省级代码
    private String province;
    // 市级代码
    private String city;
    // 主营业务
    private String mainBusiness;
    // 行业类别
    private IndustryType industryType;
    // 所在行业
    private Industry industry;
    // 商家规模
    private Scale scale;
    // 企业电话
    private String countryPhone;
    // 商家简介
    private String merchantDescription;
    // 负责人姓名
    private String principalName;
    // 负责人岗位
    private String principalJobs;
    // 负责人性别
    private Sex principalSex;
    // 负责人身份证号
    private String principalIdCard;
    @JsonFormat(pattern = "yyyy-MM-dd", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    //负责人生日
    private Date birthday;
    // 负责人邮箱地址
    private String principalEmail;
    // 证件资料文件路径（营业执照照片、法人身份证照片、推荐人身份证照片、捐赠承诺书照片、店面门头照片）
    private String certificateFile;
    // 账户code
    private String accountCode;
    // 经度
    private String longitude;
    // 纬度
    private String latitude;
    // 商圈
    private String businessCircle;

    /**
     * 获取商家Code [主键]
     *
     * @return 商家Code
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * 设置商家Code [主键]
     *
     * @param merchantCode 商家Code
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode;
    }

    /**
     * 获取商家名称
     *
     * @return 商家名称
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * 设置商家名称
     *
     * @param merchantName 商家名称
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * 获取激励模式
     *
     * @return 激励模式
     */
    public Integer getIncentiveMode() {
        return incentiveMode;
    }

    /**
     * 设置激励模式
     *
     * @param incentiveMode 激励模式
     */
    public void setIncentiveMode(Integer incentiveMode) {
        this.incentiveMode = incentiveMode;
    }

    /**
     * 获取店铺名称
     *
     * @return 店铺名称
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * 设置店铺名称
     *
     * @param shopName 店铺名称
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * 获取商家类型
     *
     * @return 商家类型
     */
    public MerchantType getMerchantType() {
        return merchantType;
    }

    /**
     * 设置商家类型
     *
     * @param merchantType 商家类型
     */
    public void setMerchantType(MerchantType merchantType) {
        this.merchantType = merchantType;
    }

    /**
     * 获取营业开始时间
     *
     * @return 营业开始时间
     */
    public String getBusinessStartTime() {
        return businessStartTime;
    }

    /**
     * 设置营业开始时间
     *
     * @param businessStartTime 营业开始时间
     */
    public void setBusinessStartTime(String businessStartTime) {
        this.businessStartTime = businessStartTime;
    }

    /**
     * 获取营业结束时间
     *
     * @return 营业结束时间
     */
    public String getBusinessEndTime() {
        return businessEndTime;
    }

    /**
     * 设置营业结束时间
     *
     * @param businessEndTime 营业结束时间
     */
    public void setBusinessEndTime(String businessEndTime) {
        this.businessEndTime = businessEndTime;
    }

    /**
     * 获取商家地址
     *
     * @return 商家地址
     */
    public String getMerchantAddress() {
        return merchantAddress;
    }

    /**
     * 设置商家地址
     *
     * @param merchantAddress 商家地址
     */
    public void setMerchantAddress(String merchantAddress) {
        this.merchantAddress = merchantAddress;
    }

    /**
     * 获取省级代码
     *
     * @return 省级代码
     */
    public String getProvince() {
        return province;
    }

    /**
     * 设置省级代码
     *
     * @param province 省级代码
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * 获取市级代码
     *
     * @return 市级代码
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置市级代码
     *
     * @param city 市级代码
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * 获取主营业务
     *
     * @return 主营业务
     */
    public String getMainBusiness() {
        return mainBusiness;
    }

    /**
     * 设置主营业务
     *
     * @param mainBusiness 主营业务
     */
    public void setMainBusiness(String mainBusiness) {
        this.mainBusiness = mainBusiness;
    }

    /**
     * 获取行业类别
     *
     * @return 行业类别
     */
    public IndustryType getIndustryType() {
        return industryType;
    }

    /**
     * 设置行业类别
     *
     * @param industryType 行业类别
     */
    public void setIndustryType(IndustryType industryType) {
        this.industryType = industryType;
    }

    /**
     * 获取所在行业
     *
     * @return 所在行业
     */
    public Industry getIndustry() {
        return industry;
    }

    /**
     * 设置所在行业
     *
     * @param industry 所在行业
     */
    public void setIndustry(Industry industry) {
        this.industry = industry;
    }

    /**
     * 获取商家规模
     *
     * @return 商家规模
     */
    public Scale getScale() {
        return scale;
    }

    /**
     * 设置商家规模
     *
     * @param scale 商家规模
     */
    public void setScale(Scale scale) {
        this.scale = scale;
    }

    /**
     * 获取企业电话
     *
     * @return 企业电话
     */
    public String getCountryPhone() {
        return countryPhone;
    }

    /**
     * 设置企业电话
     *
     * @param countryPhone 企业电话
     */
    public void setCountryPhone(String countryPhone) {
        this.countryPhone = countryPhone;
    }

    /**
     * 获取商家简介
     *
     * @return 商家简介
     */
    public String getMerchantDescription() {
        return merchantDescription;
    }

    /**
     * 设置商家简介
     *
     * @param merchantDescription 商家简介
     */
    public void setMerchantDescription(String merchantDescription) {
        this.merchantDescription = merchantDescription;
    }

    /**
     * 获取负责人姓名
     *
     * @return 负责人姓名
     */
    public String getPrincipalName() {
        return principalName;
    }

    /**
     * 设置负责人姓名
     *
     * @param principalName 负责人姓名
     */
    public void setPrincipalName(String principalName) {
        this.principalName = principalName;
    }

    /**
     * 获取负责人岗位
     *
     * @return 负责人岗位
     */
    public String getPrincipalJobs() {
        return principalJobs;
    }

    /**
     * 设置负责人岗位
     *
     * @param principalJobs 负责人岗位
     */
    public void setPrincipalJobs(String principalJobs) {
        this.principalJobs = principalJobs;
    }

    /**
     * 获取负责人性别
     *
     * @return 负责人性别
     */
    public Sex getPrincipalSex() {
        return principalSex;
    }

    /**
     * 设置负责人性别
     *
     * @param principalSex 负责人性别
     */
    public void setPrincipalSex(Sex principalSex) {
        this.principalSex = principalSex;
    }

    /**
     * 获取负责人身份证号
     *
     * @return 负责人身份证号
     */
    public String getPrincipalIdCard() {
        return principalIdCard;
    }

    /**
     * 设置负责人身份证号
     *
     * @param principalIdCard 负责人身份证号
     */
    public void setPrincipalIdCard(String principalIdCard) {
        this.principalIdCard = principalIdCard;
    }

    /**
     * 获取负责人生日
     *
     * @return 负责人生日
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * 设置负责人生日
     *
     * @param birthday 负责人生日
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * 获取负责人邮箱地址
     *
     * @return 负责人邮箱地址
     */
    public String getPrincipalEmail() {
        return principalEmail;
    }

    /**
     * 设置负责人邮箱地址
     *
     * @param principalEmail 负责人邮箱地址
     */
    public void setPrincipalEmail(String principalEmail) {
        this.principalEmail = principalEmail;
    }

    /**
     * 获取证件资料文件路径（营业执照照片、法人身份证照片、推荐人身份证照片、捐赠承诺书照片、店面门头照片）
     *
     * @return 证件资料文件路径（营业执照照片、法人身份证照片、推荐人身份证照片、捐赠承诺书照片、店面门头照片）
     */
    public String getCertificateFile() {
        return certificateFile;
    }

    /**
     * 设置证件资料文件路径（营业执照照片、法人身份证照片、推荐人身份证照片、捐赠承诺书照片、店面门头照片）
     *
     * @param certificateFile 证件资料文件路径（营业执照照片、法人身份证照片、推荐人身份证照片、捐赠承诺书照片、店面门头照片）
     */
    public void setCertificateFile(String certificateFile) {
        this.certificateFile = certificateFile;
    }

    /**
     * 获取账户code
     *
     * @return 账户code
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * 设置账户code
     *
     * @param accountCode 账户code
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

    /**
     * 获取经度
     *
     * @return 经度
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * 设置经度
     *
     * @param longitude 经度
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * 获取纬度
     *
     * @return 纬度
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * 设置纬度
     *
     * @param latitude 纬度
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * 获取商圈
     *
     * @return 商圈
     */
    public String getBusinessCircle() {
        return businessCircle;
    }

    /**
     * 设置商圈
     *
     * @param businessCircle 商圈
     */
    public void setBusinessCircle(String businessCircle) {
        this.businessCircle = businessCircle;
    }
}
