/**
 * 2016/10/14 17:22:21 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.donationreceiptapply.dao;

import com.dyb.platforms.fixfunds.services.business.donationreceiptapply.entity.DonationReceiptApply;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IbatisBaseStatement;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 收据申请 Ibatis Dao 实现
 * Created by lenovo on 2016/10/14.
 */
@Repository
public class DonationReceiptApplyDao extends IbatisDataDAOImpl<DonationReceiptApply, String> implements IDonationReceiptApplyDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="donationReceiptApplyDao" class="com.dyb.platforms.fixfunds.services.business.donationreceiptapply.entity.daos.DonationReceiptApplyDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public DonationReceiptApplyDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.dyb.platforms.fixfunds.services.business.donationreceiptapply.dao.IDonationReceiptApplyDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.dyb.platforms.fixfunds.services.business.donationreceiptapply.dao.IDonationReceiptApplyDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.dyb.platforms.fixfunds.services.business.donationreceiptapply.dao.IDonationReceiptApplyDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.dyb.platforms.fixfunds.services.business.donationreceiptapply.dao.IDonationReceiptApplyDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.dyb.platforms.fixfunds.services.business.donationreceiptapply.dao.IDonationReceiptApplyDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.dyb.platforms.fixfunds.services.business.donationreceiptapply.dao.IDonationReceiptApplyDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.dyb.platforms.fixfunds.services.business.donationreceiptapply.dao.IDonationReceiptApplyDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.dyb.platforms.fixfunds.services.business.donationreceiptapply.dao.IDonationReceiptApplyDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.dyb.platforms.fixfunds.services.business.donationreceiptapply.dao.IDonationReceiptApplyDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
