/**
 * 2016/10/14 17:22:20 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.donationreceiptapply.dao;

import com.dyb.platforms.fixfunds.services.business.donationreceiptapply.entity.DonationReceiptApply;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 收据申请 Ibatis Dao 接口
 * Created by lenovo on 2016/10/14.
 */
public interface IDonationReceiptApplyDao extends IIbatisDataDAO<DonationReceiptApply, String> {

}
