/**
 * 2016/9/27 19:51:29 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.order.dao;

import com.dyb.platforms.fixfunds.services.business.order.entity.Order;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 订单信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/27.
 */
public interface IOrderDao extends IIbatisDataDAO<Order, String> {

}
