/**
 * 2016/9/26 9:23:46 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.serviceproviders.dao;

import com.dyb.platforms.fixfunds.services.business.serviceproviders.entity.ServiceProviders;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 服务商信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/26.
 */
public interface IServiceProvidersDao extends IIbatisDataDAO<ServiceProviders, String> {

}
