/**
 * 2016/9/27 19:51:49 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.orderitem.dao;

import com.dyb.platforms.fixfunds.services.business.orderitem.entity.OrderItem;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 订单明细 Ibatis Dao 接口
 * Created by lenovo on 2016/09/27.
 */
public interface IOrderItemDao extends IIbatisDataDAO<OrderItem, String> {

}
