/**
 * 2016/10/10 10:40:33 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.conversion.entity;

import com.dyb.platforms.fixfunds.services.business.messengerbean.entity.em.MessengerBeanType;
import com.dyb.platforms.fixfunds.services.business.withdrawal.entity.em.ApplyStatus;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 转换信使豆记录
 * Created by lenovo on 2016/10/10.
 */
public class Conversion implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -9223372036854775808L;

    // 转换信使豆编号 [主键]
    private String conversionCode;
    // 转换类型
    private MessengerBeanType conversionType;
    // 申请转换的信使豆数量
    private Double applyConversionNum;
    // 实际转换的信使豆
    private Double conversionNum;
    // 代扣税
    private Double deductions;
    // 申请转换人code
    private String conversionAccount;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    // 申请时间
    private Date applyTime;
    // 申请状态
    private ApplyStatus applyStatus;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    // 创建时间
    private Date createTime;

    /** 
     * 获取转换信使豆编号 [主键]
     * 
     * @return 转换信使豆编号
     */
    public String getConversionCode() {
        return conversionCode;
    }

    /** 
     * 设置转换信使豆编号 [主键]
     * 
     * @param conversionCode 转换信使豆编号
     */
    public void setConversionCode(String conversionCode) {
        this.conversionCode = conversionCode;
    }

    /** 
     * 获取转换类型
     * 
     * @return 转换类型
     */
    public MessengerBeanType getConversionType() {
        return conversionType;
    }

    /** 
     * 设置转换类型
     * 
     * @param conversionType 转换类型
     */
    public void setConversionType(MessengerBeanType conversionType) {
        this.conversionType = conversionType;
    }

    /** 
     * 获取申请转换的信使豆数量
     * 
     * @return 申请转换的信使豆数量
     */
    public Double getApplyConversionNum() {
        return applyConversionNum;
    }

    /** 
     * 设置申请转换的信使豆数量
     * 
     * @param applyConversionNum 申请转换的信使豆数量
     */
    public void setApplyConversionNum(Double applyConversionNum) {
        this.applyConversionNum = applyConversionNum;
    }

    /** 
     * 获取实际转换的信使豆
     * 
     * @return 实际转换的信使豆
     */
    public Double getConversionNum() {
        return conversionNum;
    }

    /** 
     * 设置实际转换的信使豆
     * 
     * @param conversionNum 实际转换的信使豆
     */
    public void setConversionNum(Double conversionNum) {
        this.conversionNum = conversionNum;
    }

    /** 
     * 获取代扣税
     * 
     * @return 代扣税
     */
    public Double getDeductions() {
        return deductions;
    }

    /** 
     * 设置代扣税
     * 
     * @param deductions 代扣税
     */
    public void setDeductions(Double deductions) {
        this.deductions = deductions;
    }

    /** 
     * 获取申请转换人code
     * 
     * @return 申请转换人code
     */
    public String getConversionAccount() {
        return conversionAccount;
    }

    /** 
     * 设置申请转换人code
     * 
     * @param conversionAccount 申请转换人code
     */
    public void setConversionAccount(String conversionAccount) {
        this.conversionAccount = conversionAccount;
    }

    /** 
     * 获取申请时间
     * 
     * @return 申请时间
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /** 
     * 设置申请时间
     * 
     * @param applyTime 申请时间
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /** 
     * 获取申请状态
     * 
     * @return 申请状态
     */
    public ApplyStatus getApplyStatus() {
        return applyStatus;
    }

    /** 
     * 设置申请状态
     * 
     * @param applyStatus 申请状态
     */
    public void setApplyStatus(ApplyStatus applyStatus) {
        this.applyStatus = applyStatus;
    }

    /** 
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置创建时间
     * 
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
