/**
 * 2016/9/20 15:02:31 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.bankaccount.entity;

import com.dyb.platforms.fixfunds.services.business.recommended.entity.em.AccountType;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 银行账号
 * Created by lenovo on 2016/09/20.
 */
public class BankAccount implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -2982676077160367616L;

    // 银行账号编号 [主键]
    private String bankAccountCode;
    // 开户行
    private String bankName;
    // 开户支行
    private String bankBranch;
    // 卡号
    private String bankNum;
    // 开户名称
    private String accountName;
    // 默认设置选定
    private Boolean defaultChecked;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    // 创建时间
    private Date createTime;
    // 银行账户人code
    private String bankAccountPerson;
    // 银行账户人类型
    private AccountType bankAccountType;

    /**
     * 获取银行账号编号 [主键]
     *
     * @return 银行账号编号
     */
    public String getBankAccountCode() {
        return bankAccountCode;
    }

    /**
     * 设置银行账号编号 [主键]
     *
     * @param bankAccountCode 银行账号编号
     */
    public void setBankAccountCode(String bankAccountCode) {
        this.bankAccountCode = bankAccountCode;
    }

    /**
     * 获取开户行
     *
     * @return 开户行
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * 设置开户行
     *
     * @param bankName 开户行
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * 获取开户支行
     *
     * @return 开户支行
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /**
     * 设置开户支行
     *
     * @param bankBranch 开户支行
     */
    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch;
    }

    /**
     * 获取卡号
     *
     * @return 卡号
     */
    public String getBankNum() {
        return bankNum;
    }

    /**
     * 设置卡号
     *
     * @param bankNum 卡号
     */
    public void setBankNum(String bankNum) {
        this.bankNum = bankNum;
    }

    /**
     * 获取开户名称
     *
     * @return 开户名称
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * 设置开户名称
     *
     * @param accountName 开户名称
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * 获取默认设置选定
     *
     * @return 默认设置选定
     */
    public Boolean isDefaultChecked() {
        return defaultChecked;
    }

    /**
     * 设置默认设置选定
     *
     * @param defaultChecked 默认设置选定
     */
    public void setDefaultChecked(Boolean defaultChecked) {
        this.defaultChecked = defaultChecked;
    }

    /**
     * 获取创建时间
     *
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取银行账户人code
     *
     * @return 银行账户人code
     */
    public String getBankAccountPerson() {
        return bankAccountPerson;
    }

    /**
     * 设置银行账户人code
     *
     * @param bankAccountPerson 银行账户人code
     */
    public void setBankAccountPerson(String bankAccountPerson) {
        this.bankAccountPerson = bankAccountPerson;
    }

    /**
     * 获取银行账户人类型
     *
     * @return 银行账户人类型
     */
    public AccountType getBankAccountType() {
        return bankAccountType;
    }

    /**
     * 设置银行账户人类型
     *
     * @param bankAccountType 银行账户人类型
     */
    public void setBankAccountType(AccountType bankAccountType) {
        this.bankAccountType = bankAccountType;
    }

}
