/**
 * 2016/9/14 13:10:58 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.systemlog.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 用户操作日志
 * Created by lenovo on 2016/09/14.
 */
public class UserLog implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -9071323498651070464L;

    // 用户日志Code [主键]
    private String userLogCode;
    // 操作用户Code
    private String userCode;
    // 操作用户名称
    private String userName;
    // 操作用户的IP
    private String userLoginIp;
    // 操作类型
    private String operationType;
    // 描述
    private String description;
    // 创建时间
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /** 
     * 获取用户日志Code [主键]
     * 
     * @return 用户日志Code
     */
    public String getUserLogCode() {
        return userLogCode;
    }

    /** 
     * 设置用户日志Code [主键]
     * 
     * @param userLogCode 用户日志Code
     */
    public void setUserLogCode(String userLogCode) {
        this.userLogCode = userLogCode;
    }

    /** 
     * 获取操作用户Code
     * 
     * @return 操作用户Code
     */
    public String getUserCode() {
        return userCode;
    }

    /** 
     * 设置操作用户Code
     * 
     * @param userCode 操作用户Code
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /** 
     * 获取操作用户名称
     * 
     * @return 操作用户名称
     */
    public String getUserName() {
        return userName;
    }

    /** 
     * 设置操作用户名称
     * 
     * @param userName 操作用户名称
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /** 
     * 获取操作用户的IP
     * 
     * @return 操作用户的IP
     */
    public String getUserLoginIp() {
        return userLoginIp;
    }

    /** 
     * 设置操作用户的IP
     * 
     * @param userLoginIp 操作用户的IP
     */
    public void setUserLoginIp(String userLoginIp) {
        this.userLoginIp = userLoginIp;
    }

    /** 
     * 获取操作类型
     * 
     * @return 操作类型
     */
    public String getOperationType() {
        return operationType;
    }

    /** 
     * 设置操作类型
     * 
     * @param operationType 操作类型
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    /** 
     * 获取描述
     * 
     * @return 描述
     */
    public String getDescription() {
        return description;
    }

    /** 
     * 设置描述
     * 
     * @param description 描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** 
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置创建时间
     * 
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
