/**
 * 2016/10/10 10:32:35 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.withdrawal.entity;

import java.util.Date;

/**
 * 回购记录
 * Created by lenovo on 2016/10/10.
 */
public class Withdrawal implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -9099737479863566336L;

    // 回购编号code [主键]
    private String withdrawalCode;
    // 回购类型
    private String withdrawalType;
    // 申请回购的信使豆
    private Double applyWithdrawalNum;
    // 实际回购的信使豆
    private Double withdrawalNum;
    // 代扣税
    private Double deductions;
    // 手续费
    private Double poundage;
    // 开户行
    private String bankName;
    // 开户支行
    private String bankBranch;
    // 银行账号
    private String bankNum;
    // 开户人姓名
    private String accountName;
    // 回购人code
    private String withdrawalAccount;
    // 申请时间
    private Date applyTime;
    // 申请状态
    private String applyStatus;
    // 创建时间
    private Date createTime;

    /** 
     * 获取回购编号code [主键]
     * 
     * @return 回购编号code
     */
    public String getWithdrawalCode() {
        return withdrawalCode;
    }

    /** 
     * 设置回购编号code [主键]
     * 
     * @param withdrawalCode 回购编号code
     */
    public void setWithdrawalCode(String withdrawalCode) {
        this.withdrawalCode = withdrawalCode;
    }

    /** 
     * 获取回购类型
     * 
     * @return 回购类型
     */
    public String getWithdrawalType() {
        return withdrawalType;
    }

    /** 
     * 设置回购类型
     * 
     * @param withdrawalType 回购类型
     */
    public void setWithdrawalType(String withdrawalType) {
        this.withdrawalType = withdrawalType;
    }

    /** 
     * 获取申请回购的信使豆
     * 
     * @return 申请回购的信使豆
     */
    public Double getApplyWithdrawalNum() {
        return applyWithdrawalNum;
    }

    /** 
     * 设置申请回购的信使豆
     * 
     * @param applyWithdrawalNum 申请回购的信使豆
     */
    public void setApplyWithdrawalNum(Double applyWithdrawalNum) {
        this.applyWithdrawalNum = applyWithdrawalNum;
    }

    /** 
     * 获取实际回购的信使豆
     * 
     * @return 实际回购的信使豆
     */
    public Double getWithdrawalNum() {
        return withdrawalNum;
    }

    /** 
     * 设置实际回购的信使豆
     * 
     * @param withdrawalNum 实际回购的信使豆
     */
    public void setWithdrawalNum(Double withdrawalNum) {
        this.withdrawalNum = withdrawalNum;
    }

    /** 
     * 获取代扣税
     * 
     * @return 代扣税
     */
    public Double getDeductions() {
        return deductions;
    }

    /** 
     * 设置代扣税
     * 
     * @param deductions 代扣税
     */
    public void setDeductions(Double deductions) {
        this.deductions = deductions;
    }

    /** 
     * 获取手续费
     * 
     * @return 手续费
     */
    public Double getPoundage() {
        return poundage;
    }

    /** 
     * 设置手续费
     * 
     * @param poundage 手续费
     */
    public void setPoundage(Double poundage) {
        this.poundage = poundage;
    }

    /** 
     * 获取开户行
     * 
     * @return 开户行
     */
    public String getBankName() {
        return bankName;
    }

    /** 
     * 设置开户行
     * 
     * @param bankName 开户行
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /** 
     * 获取开户支行
     * 
     * @return 开户支行
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /** 
     * 设置开户支行
     * 
     * @param bankBranch 开户支行
     */
    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch;
    }

    /** 
     * 获取银行账号
     * 
     * @return 银行账号
     */
    public String getBankNum() {
        return bankNum;
    }

    /** 
     * 设置银行账号
     * 
     * @param bankNum 银行账号
     */
    public void setBankNum(String bankNum) {
        this.bankNum = bankNum;
    }

    /** 
     * 获取开户人姓名
     * 
     * @return 开户人姓名
     */
    public String getAccountName() {
        return accountName;
    }

    /** 
     * 设置开户人姓名
     * 
     * @param accountName 开户人姓名
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /** 
     * 获取回购人code
     * 
     * @return 回购人code
     */
    public String getWithdrawalAccount() {
        return withdrawalAccount;
    }

    /** 
     * 设置回购人code
     * 
     * @param withdrawalAccount 回购人code
     */
    public void setWithdrawalAccount(String withdrawalAccount) {
        this.withdrawalAccount = withdrawalAccount;
    }

    /** 
     * 获取申请时间
     * 
     * @return 申请时间
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /** 
     * 设置申请时间
     * 
     * @param applyTime 申请时间
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /** 
     * 获取申请状态
     * 
     * @return 申请状态
     */
    public String getApplyStatus() {
        return applyStatus;
    }

    /** 
     * 设置申请状态
     * 
     * @param applyStatus 申请状态
     */
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus;
    }

    /** 
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置创建时间
     * 
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
