/**
 * 2015/4/24 11:35:34 Caven created.
 * Generated by Caven.CodeBuilder (funiJava.enum 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.businessprocess.entity.em;

/**
 * 枚举：业务单状态
 * Created by Caven on 2015/04/24.
 */
public enum BusinessDocStatus {
    /**
     * 未提交
     */
    未提交,
    /**
     *
     */
    受理中,
    /**
     * 已提交、办理中
     */
    办理中,
    /**
     * 归档中
     */
    归档中,
    /**
     * 业务已完成，办理已完成
     */
    已完成,
    /**
     * 已暂停
     */
    已暂停,
    /**
     * 业务已撤销
     */
    已撤销;
}
