/**
 * 2015/4/24 11:35:34 Caven created.
 * Generated by Caven.CodeBuilder (funiJava.enum 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.businessprocess.entity.em;

/**
 * 枚举：要件类型
 * Created by Caven on 2015/04/24.
 */
public enum BusinessPaperType {
    /**
     *
     */
    用户要件,
    /**
     *
     */
    过程要件;
}
