/**
 * 2016/9/11 15:57:29 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.user.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 权限信息
 * Created by lenovo on 2016/09/11.
 */
public class Permissions implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -4595124076397681152L;

    // 权限Code [主键]
    private String permissionsCode;
    // 序号
    private int sequence;
    // 权限名称
    private String permissionsName;
    // 是否为叶子节点
    private Boolean leaf;
    // 权限URL
    private String permissionsUrl;
    // 图片
    private String image;
    // 父级菜单Code
    private String parentCode;
    // 描述
    private String description;
    // 创建时间
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /** 
     * 获取权限Code [主键]
     * 
     * @return 权限Code
     */
    public String getPermissionsCode() {
        return permissionsCode;
    }

    /** 
     * 设置权限Code [主键]
     * 
     * @param permissionsCode 权限Code
     */
    public void setPermissionsCode(String permissionsCode) {
        this.permissionsCode = permissionsCode;
    }

    /** 
     * 获取序号
     * 
     * @return 序号
     */
    public int getSequence() {
        return sequence;
    }

    /** 
     * 设置序号
     * 
     * @param sequence 序号
     */
    public void setSequence(int sequence) {
        this.sequence = sequence;
    }

    /** 
     * 获取权限名称
     * 
     * @return 权限名称
     */
    public String getPermissionsName() {
        return permissionsName;
    }

    /** 
     * 设置权限名称
     * 
     * @param permissionsName 权限名称
     */
    public void setPermissionsName(String permissionsName) {
        this.permissionsName = permissionsName;
    }

    /** 
     * 获取描述
     * 
     * @return 描述
     */
    public String getDescription() {
        return description;
    }

    /** 
     * 设置描述
     * 
     * @param description 描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** 
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置创建时间
     * 
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /** 
     * 获取是否为叶子节点
     * 
     * @return 是否为叶子节点
     */
    public Boolean isLeaf() {
        return leaf;
    }

    /** 
     * 设置是否为叶子节点
     * 
     * @param leaf 是否为叶子节点
     */
    public void setLeaf(Boolean leaf) {
        this.leaf = leaf;
    }

    /** 
     * 获取权限URL
     * 
     * @return 权限URL
     */
    public String getPermissionsUrl() {
        return permissionsUrl;
    }

    /** 
     * 设置权限URL
     * 
     * @param permissionsUrl 权限URL
     */
    public void setPermissionsUrl(String permissionsUrl) {
        this.permissionsUrl = permissionsUrl;
    }

    /** 
     * 获取图片
     * 
     * @return 图片
     */
    public String getImage() {
        return image;
    }

    /** 
     * 设置图片
     * 
     * @param image 图片
     */
    public void setImage(String image) {
        this.image = image;
    }

    /** 
     * 获取父级菜单Code
     * 
     * @return 父级菜单Code
     */
    public String getParentCode() {
        return parentCode;
    }

    /** 
     * 设置父级菜单Code
     * 
     * @param parentCode 父级菜单Code
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

}
