/**
 * 2016/9/11 15:51:42 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.user.entity;

/**
 * 角色权限组
 * Created by lenovo on 2016/09/11.
 */
public class RolePermissions implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -9223372036854775808L;

    // 角色Code [主键]
    private String roleCode;
    // 用户Code
    private String permissionsCode;

    /** 
     * 获取角色Code [主键]
     * 
     * @return 角色Code
     */
    public String getRoleCode() {
        return roleCode;
    }

    /** 
     * 设置角色Code [主键]
     * 
     * @param roleCode 角色Code
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /** 
     * 获取用户Code
     * 
     * @return 用户Code
     */
    public String getPermissionsCode() {
        return permissionsCode;
    }

    /** 
     * 设置用户Code
     * 
     * @param permissionsCode 用户Code
     */
    public void setPermissionsCode(String permissionsCode) {
        this.permissionsCode = permissionsCode;
    }

}
