/**
 * 2016/9/11 15:45:20 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.user.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 角色信息
 * Created by lenovo on 2016/09/11.
 */
public class Role implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -5134480635232516096L;

    // 角色Code [主键]
    private String roleCode;
    // 序号
    private int sequence;
    // 角色名称
    private String roleName;
    // 描述
    private String description;
    // 创建时间
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /** 
     * 获取角色Code [主键]
     * 
     * @return 角色Code
     */
    public String getRoleCode() {
        return roleCode;
    }

    /** 
     * 设置角色Code [主键]
     * 
     * @param roleCode 角色Code
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /** 
     * 获取序号
     * 
     * @return 序号
     */
    public int getSequence() {
        return sequence;
    }

    /** 
     * 设置序号
     * 
     * @param sequence 序号
     */
    public void setSequence(int sequence) {
        this.sequence = sequence;
    }

    /** 
     * 获取角色名称
     * 
     * @return 角色名称
     */
    public String getRoleName() {
        return roleName;
    }

    /** 
     * 设置角色名称
     * 
     * @param roleName 角色名称
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /** 
     * 获取描述
     * 
     * @return 描述
     */
    public String getDescription() {
        return description;
    }

    /** 
     * 设置描述
     * 
     * @param description 描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** 
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置创建时间
     * 
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
