/**
 * 2016/3/1 16:08:01 Administrator created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.user.entity;

/**
 * 用户模块
 * Created by Administrator on 2016/03/01.
 */
public class User implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -9223372036854775808L;

    // 用户主键 [主键]
    private String userCode;
    // 用户姓名
    private String userName;
    // 用户密码
    private String userPassword;

    /**
     * 获取用户主键 [主键]
     *
     * @return 用户主键
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * 设置用户主键 [主键]
     *
     * @param userCode 用户主键
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * 获取用户姓名
     *
     * @return 用户姓名
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 设置用户姓名
     *
     * @param userName 用户姓名
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * 获取用户密码
     *
     * @return 用户密码
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * 设置用户密码
     *
     * @param userPassword 用户密码
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

}
