/**
 * 2016/9/11 11:07:34 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.user.entity;

import com.dyb.platforms.fixfunds.services.business.user.entity.em.UserStatus;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 用户信息
 * Created by lenovo on 2016/09/11.
 */
public class User implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -9223372036854775808L;

    // 用户Code [主键]
    private String userCode;
    // 序号
    private int sequence;
    // 用户名称
    private String userName;
    // 用户密码
    private String userPassword;
    // 用户状态
    private UserStatus status;
    // 描述
    private String description;
    // 创建时间
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * 获取用户Code [主键]
     *
     * @return 用户Code
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * 设置用户Code [主键]
     *
     * @param userCode 用户Code
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * 获取序号
     *
     * @return 序号
     */
    public int getSequence() {
        return sequence;
    }

    /**
     * 设置序号
     *
     * @param sequence 序号
     */
    public void setSequence(int sequence) {
        this.sequence = sequence;
    }

    /**
     * 获取用户名称
     *
     * @return 用户名称
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 设置用户名称
     *
     * @param userName 用户名称
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * 获取用户密码
     *
     * @return 用户密码
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * 设置用户密码
     *
     * @param userPassword 用户密码
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * 获取用户状态
     *
     * @return 用户状态
     */
    public UserStatus getStatus() {
        return status;
    }

    /**
     * 设置用户状态
     *
     * @param status 用户状态
     */
    public void setStatus(UserStatus status) {
        this.status = status;
    }

    /**
     * 获取描述
     *
     * @return 描述
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置描述
     *
     * @param description 描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 获取创建时间
     *
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
