/**
 * 2016/9/11 15:52:09 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.user.entity;

/**
 * 用户角色组
 * Created by lenovo on 2016/09/11.
 */
public class UserRole implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -6272697330579486720L;

    // 用户Code [主键]
    private String userCode;
    // 角色Code
    private String roleCode;

    /** 
     * 获取用户Code [主键]
     * 
     * @return 用户Code
     */
    public String getUserCode() {
        return userCode;
    }

    /** 
     * 设置用户Code [主键]
     * 
     * @param userCode 用户Code
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /** 
     * 获取角色Code
     * 
     * @return 角色Code
     */
    public String getRoleCode() {
        return roleCode;
    }

    /** 
     * 设置角色Code
     * 
     * @param roleCode 角色Code
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

}
