/**
 * 2016/9/11 16:06:39 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.systemparams.dao;

import com.dyb.platforms.fixfunds.services.business.systemparams.entity.SystemParams;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 系统参数信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/11.
 */
public interface ISystemParamsDao extends IIbatisDataDAO<SystemParams, String> {

}
