/**
 * 2016/10/14 19:56:08 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.dao;

import com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.entity.ConversionInvoiceDetails;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IbatisBaseStatement;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 转换发票明细 Ibatis Dao 实现
 * Created by lenovo on 2016/10/14.
 */
@Repository
public class ConversionInvoiceDetailsDao extends IbatisDataDAOImpl<ConversionInvoiceDetails, String> implements IConversionInvoiceDetailsDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="conversionInvoiceDetailsDao" class="com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.entity.daos.ConversionInvoiceDetailsDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public ConversionInvoiceDetailsDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.dao.IConversionInvoiceDetailsDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.dao.IConversionInvoiceDetailsDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.dao.IConversionInvoiceDetailsDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.dao.IConversionInvoiceDetailsDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.dao.IConversionInvoiceDetailsDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.dao.IConversionInvoiceDetailsDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.dao.IConversionInvoiceDetailsDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.dao.IConversionInvoiceDetailsDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.dao.IConversionInvoiceDetailsDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
