/**
 * 2016/10/14 19:56:08 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.dao;

import com.dyb.platforms.fixfunds.services.business.conversioninvoicedetails.entity.ConversionInvoiceDetails;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 转换发票明细 Ibatis Dao 接口
 * Created by lenovo on 2016/10/14.
 */
public interface IConversionInvoiceDetailsDao extends IIbatisDataDAO<ConversionInvoiceDetails, String> {

}
