/**
 * 2016/9/20 14:24:26 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.member.entity;

import com.dyb.platforms.fixfunds.services.business.member.entity.em.Certificate;
import com.dyb.platforms.fixfunds.services.business.member.entity.em.MemberStatus;
import com.dyb.platforms.fixfunds.services.business.member.entity.em.MemberType;
import com.dyb.platforms.fixfunds.services.business.merchant.entity.em.Industry;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 信使信息
 * Created by lenovo on 2016/09/20.
 */
public class Member implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -7028689592624404480L;

    // 信使编号code [主键]
    private String memberCode;
    // 用户名
    private String memberName;
    // 类别
    private MemberType memberType;
    // 真实姓名
    private String realName;
    // 性别
    private String sex;
    // 籍贯
    private String nativePlace;
    // 证件类型
    private Certificate certificate;
    // 证件号码
    private String certificateNumber;
    // 手机号
    private String memberPhone;
    // 所在行业
    private Industry industry;
    // 生日
    private Date birthday;
    // 个人邮箱
    private String memberEmail;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    // 注册时间
    private Date createTime;
    // 登陆密码
    private String password;
    // 二级密码
    private String tradePassword;
    // 信使状态
    private MemberStatus memberStatus;

    /**
     * 获取信使编号code [主键]
     *
     * @return 信使编号code
     */
    public String getMemberCode() {
        return memberCode;
    }

    /**
     * 设置信使编号code [主键]
     *
     * @param memberCode 信使编号code
     */
    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode;
    }

    /**
     * 获取用户名
     *
     * @return 用户名
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * 设置用户名
     *
     * @param memberName 用户名
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName;
    }

    /**
     * 获取类别
     *
     * @return 类别
     */
    public MemberType getMemberType() {
        return memberType;
    }

    /**
     * 设置类别
     *
     * @param memberType 类别
     */
    public void setMemberType(MemberType memberType) {
        this.memberType = memberType;
    }

    /**
     * 获取真实姓名
     *
     * @return 真实姓名
     */
    public String getRealName() {
        return realName;
    }

    /**
     * 设置真实姓名
     *
     * @param realName 真实姓名
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * 获取性别
     *
     * @return 性别
     */
    public String getSex() {
        return sex;
    }

    /**
     * 设置性别
     *
     * @param sex 性别
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * 获取籍贯
     *
     * @return 籍贯
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * 设置籍贯
     *
     * @param nativePlace 籍贯
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    /**
     * 获取证件类型
     *
     * @return 证件类型
     */
    public Certificate getCertificate() {
        return certificate;
    }

    /**
     * 设置证件类型
     *
     * @param certificate 证件类型
     */
    public void setCertificate(Certificate certificate) {
        this.certificate = certificate;
    }

    /**
     * 获取证件号码
     *
     * @return 证件号码
     */
    public String getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * 设置证件号码
     *
     * @param certificateNumber 证件号码
     */
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber;
    }

    /**
     * 获取手机号
     *
     * @return 手机号
     */
    public String getMemberPhone() {
        return memberPhone;
    }

    /**
     * 设置手机号
     *
     * @param memberPhone 手机号
     */
    public void setMemberPhone(String memberPhone) {
        this.memberPhone = memberPhone;
    }

    /**
     * 获取所在行业
     *
     * @return 所在行业
     */
    public Industry getIndustry() {
        return industry;
    }

    /**
     * 设置所在行业
     *
     * @param industry 所在行业
     */
    public void setIndustry(Industry industry) {
        this.industry = industry;
    }

    /**
     * 获取生日
     *
     * @return 生日
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * 设置生日
     *
     * @param birthday 生日
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * 获取个人邮箱
     *
     * @return 个人邮箱
     */
    public String getMemberEmail() {
        return memberEmail;
    }

    /**
     * 设置个人邮箱
     *
     * @param memberEmail 个人邮箱
     */
    public void setMemberEmail(String memberEmail) {
        this.memberEmail = memberEmail;
    }

    /**
     * 获取注册时间
     *
     * @return 注册时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置注册时间
     *
     * @param createTime 注册时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取登陆密码
     *
     * @return 登陆密码
     */
    public String getPassword() {
        return password;
    }

    /**
     * 设置登陆密码
     *
     * @param password 登陆密码
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * 获取二级密码
     *
     * @return 二级密码
     */
    public String getTradePassword() {
        return tradePassword;
    }

    /**
     * 设置二级密码
     *
     * @param tradePassword 二级密码
     */
    public void setTradePassword(String tradePassword) {
        this.tradePassword = tradePassword;
    }

    /**
     * 获取信使状态
     *
     * @return 信使状态
     */
    public MemberStatus getMemberStatus() {
        return memberStatus;
    }

    /**
     * 设置信使状态
     *
     * @param memberStatus 信使状态
     */
    public void setMemberStatus(MemberStatus memberStatus) {
        this.memberStatus = memberStatus;
    }

}
