/**
 * 2016/9/18 19:24:05 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.businessprocess.entity;

import com.dyb.platforms.fixfunds.services.business.businessprocess.entity.em.BusinessPaperType;

/**
 * 业务单要件
 * Created by lenovo on 2016/09/18.
 */
public class BusinessPaper implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -2079063203222613248L;

    // 业务单要件编号 [主键]
    private String businessPaperCode;
    // 要件名称
    private String paperName;
    // 要件类型
    private BusinessPaperType paperType;
    // 业务单号
    private String docCode;

    /**
     * 获取业务单要件编号 [主键]
     *
     * @return 业务单要件编号
     */
    public String getBusinessPaperCode() {
        return businessPaperCode;
    }

    /**
     * 设置业务单要件编号 [主键]
     *
     * @param businessPaperCode 业务单要件编号
     */
    public void setBusinessPaperCode(String businessPaperCode) {
        this.businessPaperCode = businessPaperCode;
    }

    /**
     * 获取要件名称
     *
     * @return 要件名称
     */
    public String getPaperName() {
        return paperName;
    }

    /**
     * 设置要件名称
     *
     * @param paperName 要件名称
     */
    public void setPaperName(String paperName) {
        this.paperName = paperName;
    }

    /**
     * 获取要件类型
     *
     * @return 要件类型
     */
    public BusinessPaperType getPaperType() {
        return paperType;
    }

    /**
     * 设置要件类型
     *
     * @param paperType 要件类型
     */
    public void setPaperType(BusinessPaperType paperType) {
        this.paperType = paperType;
    }

    /**
     * 获取业务单号
     *
     * @return 业务单号
     */
    public String getDocCode() {
        return docCode;
    }

    /**
     * 设置业务单号
     *
     * @param docCode 业务单号
     */
    public void setDocCode(String docCode) {
        this.docCode = docCode;
    }

}
