/**
 * 2016/9/18 19:24:06 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.businessprocess.entity;

import com.dyb.platforms.fixfunds.services.business.businessprocess.entity.em.BusinessDocStatus;

import java.util.Date;

/**
 * 业务单操作记录
 * Created by lenovo on 2016/09/18.
 */
public class BusinessRunRecord implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -6680869351458209792L;

    // 业务单操作记录编码 [主键]
    private String businessRunRecordCode;
    // 执行人
    private String runner;
    // 执行时间
    private Date runTime;
    // 执行内容
    private String content;
    // 业务单编号
    private String docCode;
    // 业务单状态
    private BusinessDocStatus businessStatus;

    /**
     * 获取业务单操作记录编码 [主键]
     *
     * @return 业务单操作记录编码
     */
    public String getBusinessRunRecordCode() {
        return businessRunRecordCode;
    }

    /**
     * 设置业务单操作记录编码 [主键]
     *
     * @param businessRunRecordCode 业务单操作记录编码
     */
    public void setBusinessRunRecordCode(String businessRunRecordCode) {
        this.businessRunRecordCode = businessRunRecordCode;
    }

    /**
     * 获取执行人
     *
     * @return 执行人
     */
    public String getRunner() {
        return runner;
    }

    /**
     * 设置执行人
     *
     * @param runner 执行人
     */
    public void setRunner(String runner) {
        this.runner = runner;
    }

    /**
     * 获取执行时间
     *
     * @return 执行时间
     */
    public Date getRunTime() {
        return runTime;
    }

    /**
     * 设置执行时间
     *
     * @param runTime 执行时间
     */
    public void setRunTime(Date runTime) {
        this.runTime = runTime;
    }

    /**
     * 获取执行内容
     *
     * @return 执行内容
     */
    public String getContent() {
        return content;
    }

    /**
     * 设置执行内容
     *
     * @param content 执行内容
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 获取业务单编号
     *
     * @return 业务单编号
     */
    public String getDocCode() {
        return docCode;
    }

    /**
     * 设置业务单编号
     *
     * @param docCode 业务单编号
     */
    public void setDocCode(String docCode) {
        this.docCode = docCode;
    }

    /**
     * 获取业务单状态
     *
     * @return 业务单状态
     */
    public BusinessDocStatus getBusinessStatus() {
        return businessStatus;
    }

    /**
     * 设置业务单状态
     *
     * @param businessStatus 业务单状态
     */
    public void setBusinessStatus(BusinessDocStatus businessStatus) {
        this.businessStatus = businessStatus;
    }

}
