/**
 * 2016/9/18 19:24:05 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.businessprocess.entity;

import com.dyb.platforms.fixfunds.services.business.businessprocess.entity.em.BusinessDocStatus;
import com.dyb.platforms.fixfunds.services.utils.core.bean.BaseBean;

/**
 * 业务单头
 * Created by lenovo on 2016/09/18.
 */
public class BusinessDocHead extends BaseBean implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -9223372036854775808L;

    // 业务单编号 [主键]
    private String docCode;
    // 摘要
    private String summary;
    // 业务单状态
    private BusinessDocStatus businessDocStatus;
    // 业务类型
    private int businessType;
    // 业务单主题对象keyCode
    private String bodyKeyCode;
    // 业务单主体对象类型名称
    private String bodyClassName;
    // 是否执行
    private boolean runned;
    // 是否确认
    private boolean confirmed;
    // 联系人
    private String linkMan;
    // 联系电话
    private String linkManTel;
    // 备注
    private String remark;

    /**
     * 获取业务单编号 [主键]
     *
     * @return 业务单编号
     */
    public String getDocCode() {
        return docCode;
    }

    /**
     * 设置业务单编号 [主键]
     *
     * @param docCode 业务单编号
     */
    public void setDocCode(String docCode) {
        this.docCode = docCode;
    }

    /**
     * 获取摘要
     *
     * @return 摘要
     */
    public String getSummary() {
        return summary;
    }

    /**
     * 设置摘要
     *
     * @param summary 摘要
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * 获取业务单状态
     *
     * @return 业务单状态
     */
    public BusinessDocStatus getBusinessDocStatus() {
        return businessDocStatus;
    }

    /**
     * 设置业务单状态
     *
     * @param businessDocStatus 业务单状态
     */
    public void setBusinessDocStatus(BusinessDocStatus businessDocStatus) {
        this.businessDocStatus = businessDocStatus;
    }

    /**
     * 获取业务类型
     *
     * @return 业务类型
     */
    public int getBusinessType() {
        return businessType;
    }

    /**
     * 设置业务类型
     *
     * @param businessType 业务类型
     */
    public void setBusinessType(int businessType) {
        this.businessType = businessType;
    }

    /**
     * 获取业务单主题对象keyCode
     *
     * @return 业务单主题对象keyCode
     */
    public String getBodyKeyCode() {
        return bodyKeyCode;
    }

    /**
     * 设置业务单主题对象keyCode
     *
     * @param bodyKeyCode 业务单主题对象keyCode
     */
    public void setBodyKeyCode(String bodyKeyCode) {
        this.bodyKeyCode = bodyKeyCode;
    }

    /**
     * 获取业务单主体对象类型名称
     *
     * @return 业务单主体对象类型名称
     */
    public String getBodyClassName() {
        return bodyClassName;
    }

    /**
     * 设置业务单主体对象类型名称
     *
     * @param bodyClassName 业务单主体对象类型名称
     */
    public void setBodyClassName(String bodyClassName) {
        this.bodyClassName = bodyClassName;
    }

    /**
     * 获取是否执行
     *
     * @return 是否执行
     */
    public boolean isRunned() {
        return runned;
    }

    /**
     * 设置是否执行
     *
     * @param runned 是否执行
     */
    public void setRunned(boolean runned) {
        this.runned = runned;
    }

    /**
     * 获取是否确认
     *
     * @return 是否确认
     */
    public boolean isConfirmed() {
        return confirmed;
    }

    /**
     * 设置是否确认
     *
     * @param confirmed 是否确认
     */
    public void setConfirmed(boolean confirmed) {
        this.confirmed = confirmed;
    }

    /**
     * 获取联系人
     *
     * @return 联系人
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * 设置联系人
     *
     * @param linkMan 联系人
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan;
    }

    /**
     * 获取联系电话
     *
     * @return 联系电话
     */
    public String getLinkManTel() {
        return linkManTel;
    }

    /**
     * 设置联系电话
     *
     * @param linkManTel 联系电话
     */
    public void setLinkManTel(String linkManTel) {
        this.linkManTel = linkManTel;
    }

    /**
     * 获取备注
     *
     * @return 备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置备注
     *
     * @param remark 备注
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

}
