/**
 * 2016/10/20 16:54:03 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.salesman.entity;

import com.dyb.platforms.fixfunds.services.business.member.entity.em.Certificate;
import com.dyb.platforms.fixfunds.services.business.merchant.entity.em.Industry;

import java.util.Date;

/**
 * 业务员信息
 * Created by lenovo on 2016/10/20.
 */
public class Salesman implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -1830999498176853760L;

    // 业务员编号code [主键]
    private String salesmanCode;
    // 真实姓名
    private String realName;
    // 性别
    private String sex;
    // 籍贯
    private String nativePlace;
    // 省级代码
    private String province;
    // 市级代码
    private String city;
    // 证件类型
    private Certificate certificate;
    // 证件号码
    private String certificateNumber;
    // 所在行业
    private Industry industry;
    // 生日
    private Date birthday;
    // 个人邮箱
    private String salesmanEmail;
    // 激励比例
    private String incentiveProportion;
    // 账户Code
    private String accountCode;

    /**
     * 获取业务员编号code [主键]
     *
     * @return 业务员编号code
     */
    public String getSalesmanCode() {
        return salesmanCode;
    }

    /**
     * 设置业务员编号code [主键]
     *
     * @param salesmanCode 业务员编号code
     */
    public void setSalesmanCode(String salesmanCode) {
        this.salesmanCode = salesmanCode;
    }

    /**
     * 获取真实姓名
     *
     * @return 真实姓名
     */
    public String getRealName() {
        return realName;
    }

    /**
     * 设置真实姓名
     *
     * @param realName 真实姓名
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * 获取性别
     *
     * @return 性别
     */
    public String getSex() {
        return sex;
    }

    /**
     * 设置性别
     *
     * @param sex 性别
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * 获取籍贯
     *
     * @return 籍贯
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * 设置籍贯
     *
     * @param nativePlace 籍贯
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    /**
     * 获取省级代码
     *
     * @return 省级代码
     */
    public String getProvince() {
        return province;
    }

    /**
     * 设置省级代码
     *
     * @param province 省级代码
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * 获取市级代码
     *
     * @return 市级代码
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置市级代码
     *
     * @param city 市级代码
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * 获取证件类型
     *
     * @return 证件类型
     */
    public Certificate getCertificate() {
        return certificate;
    }

    /**
     * 设置证件类型
     *
     * @param certificate 证件类型
     */
    public void setCertificate(Certificate certificate) {
        this.certificate = certificate;
    }

    /**
     * 获取证件号码
     *
     * @return 证件号码
     */
    public String getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * 设置证件号码
     *
     * @param certificateNumber 证件号码
     */
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber;
    }

    /**
     * 获取所在行业
     *
     * @return 所在行业
     */
    public Industry getIndustry() {
        return industry;
    }

    /**
     * 设置所在行业
     *
     * @param industry 所在行业
     */
    public void setIndustry(Industry industry) {
        this.industry = industry;
    }

    /**
     * 获取生日
     *
     * @return 生日
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * 设置生日
     *
     * @param birthday 生日
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * 获取个人邮箱
     *
     * @return 个人邮箱
     */
    public String getSalesmanEmail() {
        return salesmanEmail;
    }

    /**
     * 设置个人邮箱
     *
     * @param salesmanEmail 个人邮箱
     */
    public void setSalesmanEmail(String salesmanEmail) {
        this.salesmanEmail = salesmanEmail;
    }

    /**
     * 获取激励比例
     *
     * @return 激励比例
     */
    public String getIncentiveProportion() {
        return incentiveProportion;
    }

    /**
     * 设置激励比例
     *
     * @param incentiveProportion 激励比例
     */
    public void setIncentiveProportion(String incentiveProportion) {
        this.incentiveProportion = incentiveProportion;
    }

    /**
     * 获取账户Code
     *
     * @return 账户Code
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * 设置账户Code
     *
     * @param accountCode 账户Code
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

}
