/**
 * 2016/10/8 15:36:19 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.blacklist.entity;

import java.util.Date;

/**
 * 黑名单
 * Created by lenovo on 2016/10/08.
 */
public class Blacklist implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -8579853046024150016L;

    // 黑名单code [主键]
    private String blacklistCode;
    // 拉黑的商家code
    private String merchantCode;
    // 拉黑原因
    private String blackDescption;
    // 创建时间
    private Date createTime;

    /** 
     * 获取黑名单code [主键]
     * 
     * @return 黑名单code
     */
    public String getBlacklistCode() {
        return blacklistCode;
    }

    /** 
     * 设置黑名单code [主键]
     * 
     * @param blacklistCode 黑名单code
     */
    public void setBlacklistCode(String blacklistCode) {
        this.blacklistCode = blacklistCode;
    }

    /** 
     * 获取拉黑的商家code
     * 
     * @return 拉黑的商家code
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /** 
     * 设置拉黑的商家code
     * 
     * @param merchantCode 拉黑的商家code
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode;
    }

    /** 
     * 获取拉黑原因
     * 
     * @return 拉黑原因
     */
    public String getBlackDescption() {
        return blackDescption;
    }

    /** 
     * 设置拉黑原因
     * 
     * @param blackDescption 拉黑原因
     */
    public void setBlackDescption(String blackDescption) {
        this.blackDescption = blackDescption;
    }

    /** 
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置创建时间
     * 
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
