/**
 * 2015/4/24 11:35:30 Caven created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.utils.core.configureations;

import java.util.List;

/**
 * 业务定义
 * Created by Caven on 2015/04/24.
 */
public class BusinessDefined implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -8559999446645379072L;

    // 业务类型 [主键]
    private int businessType;
    // 业务类型名称
    private String name;
    // 流程文件,classpath:前缀为类路径，file:前缀为文件路径，无前缀默认为文件路径
    private String flowFile;
    // 流程Key
    private String flowKey;
    // 超期时间（单位天）
    private int overdue;
    // 业务入口视图的模块名称
    private String moduleName;
    // 业务入口视图的视图名称
    private String viewName;
    // 业务要件定义列表
    private List<BusinessPaperDefined> papers;

    /**
     * 获取业务类型 [主键]
     *
     * @return 业务类型
     */
    public int getBusinessType() {
        return businessType;
    }

    /**
     * 设置业务类型 [主键]
     *
     * @param businessType 业务类型
     */
    public void setBusinessType(int businessType) {
        this.businessType = businessType;
    }

    /**
     * 获取业务类型名称
     *
     * @return 业务类型名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置业务类型名称
     *
     * @param name 业务类型名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取流程文件,classpath:前缀为类路径，file:前缀为文件路径，无前缀默认为文件路径
     *
     * @return 流程文件, classpath:前缀为类路径，file:前缀为文件路径，无前缀默认为文件路径
     */
    public String getFlowFile() {
        return flowFile;
    }

    /**
     * 设置流程文件,classpath:前缀为类路径，file:前缀为文件路径，无前缀默认为文件路径
     *
     * @param flowFile 流程文件,classpath:前缀为类路径，file:前缀为文件路径，无前缀默认为文件路径
     */
    public void setFlowFile(String flowFile) {
        this.flowFile = flowFile;
    }

    /**
     * 获取流程Key
     *
     * @return 流程Key
     */
    public String getFlowKey() {
        return flowKey;
    }

    /**
     * 设置流程Key
     *
     * @param flowKey 流程Key
     */
    public void setFlowKey(String flowKey) {
        this.flowKey = flowKey;
    }

    /**
     * 获取超期时间（单位天）
     *
     * @return 超期时间（单位天）
     */
    public int getOverdue() {
        return overdue;
    }

    /**
     * 设置超期时间（单位天）
     *
     * @param overdue 超期时间（单位天）
     */
    public void setOverdue(int overdue) {
        this.overdue = overdue;
    }

    /**
     * 获取业务入口视图的模块名称
     *
     * @return 业务入口视图的模块名称
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * 设置业务入口视图的模块名称
     *
     * @param moduleName 业务入口视图的模块名称
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * 获取业务入口视图的视图名称
     *
     * @return 业务入口视图的视图名称
     */
    public String getViewName() {
        return viewName;
    }

    /**
     * 设置业务入口视图的视图名称
     *
     * @param viewName 业务入口视图的视图名称
     */
    public void setViewName(String viewName) {
        this.viewName = viewName;
    }

    /**
     * 获取业务要件定义列表
     *
     * @return 业务要件定义列表
     */
    public List<BusinessPaperDefined> getPapers() {
        return papers;
    }

    /**
     * 设置业务要件定义列表
     *
     * @param papers 业务要件定义列表
     */
    public void setPapers(List<BusinessPaperDefined> papers) {
        this.papers = papers;
    }

}
