/**
 * 2016/9/18 18:30:51 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.binarydata.entity;

import java.util.Date;

/**
 * 大数据存储
 * Created by lenovo on 2016/09/18.
 */
public class BinaryData implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -9223372036854775808L;

    // 外键key [主键]
    private String keyId;
    // 内容
    private byte[] content;
    // 创建时间
    private Date createTime;

    /** 
     * 获取外键key [主键]
     * 
     * @return 外键key
     */
    public String getKeyId() {
        return keyId;
    }

    /** 
     * 设置外键key [主键]
     * 
     * @param keyId 外键key
     */
    public void setKeyId(String keyId) {
        this.keyId = keyId;
    }

    /** 
     * 获取内容
     * 
     * @return 内容
     */
    public byte[] getContent() {
        return content;
    }

    /** 
     * 设置内容
     * 
     * @param content 内容
     */
    public void setContent(byte[] content) {
        this.content = content;
    }

    /** 
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置创建时间
     * 
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
