/**
 * 2016/10/10 10:33:57 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.invoiceapply.dao;

import com.dyb.platforms.fixfunds.services.business.invoiceapply.entity.InvoiceApply;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 让利款发票申请 Ibatis Dao 接口
 * Created by lenovo on 2016/10/10.
 */
public interface IInvoiceApplyDao extends IIbatisDataDAO<InvoiceApply, String> {

}
