/**
 * 2016/9/20 14:59:47 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.bankaccount.dao;

import com.dyb.platforms.fixfunds.services.business.bankaccount.entity.BankAccount;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 银行账号 Ibatis Dao 接口
 * Created by lenovo on 2016/09/20.
 */
public interface IBankAccountDao extends IIbatisDataDAO<BankAccount, String> {

}
