/**
 * 2016/9/18 18:30:51 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.binarydata.dao;

import com.dyb.platforms.fixfunds.services.business.binarydata.entity.BinaryData;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 大数据存储 Ibatis Dao 接口
 * Created by lenovo on 2016/09/18.
 */
public interface IBinaryDataDao extends IIbatisDataDAO<BinaryData, String> {

}
