/**
 * 2016/10/10 10:31:05 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.transfer.dao;

import com.dyb.platforms.fixfunds.services.business.transfer.entity.Transfer;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 转赠 Ibatis Dao 接口
 * Created by lenovo on 2016/10/10.
 */
public interface ITransferDao extends IIbatisDataDAO<Transfer, String> {

}
