/**
 * 2016/9/26 9:13:01 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.account.dao;

import com.dyb.platforms.fixfunds.services.business.account.entity.Account;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 账号信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/26.
 */
public interface IAccountDao extends IIbatisDataDAO<Account, String> {

}
