/**
 * 2016/9/27 20:15:32 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.sendaddress.dao;

import com.dyb.platforms.fixfunds.services.business.sendaddress.entity.SendAddress;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 寄送地址 Ibatis Dao 接口
 * Created by lenovo on 2016/09/27.
 */
public interface ISendAddressDao extends IIbatisDataDAO<SendAddress, String> {

}
