/**
 * 2016/9/20 11:17:51 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.merchant.dao;

import com.dyb.platforms.fixfunds.services.business.merchant.entity.Merchant;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 商家信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/20.
 */
public interface IMerchantDao extends IIbatisDataDAO<Merchant, String> {

}
