/**
 * 2016/9/20 11:17:51 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.merchant.dao;

import com.dyb.platforms.fixfunds.services.business.merchant.entity.Merchant;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IbatisBaseStatement;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 商家信息 Ibatis Dao 实现
 * Created by lenovo on 2016/09/20.
 */
@Repository
public class MerchantDao extends IbatisDataDAOImpl<Merchant, String> implements IMerchantDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="merchantDao" class="com.dyb.platforms.fixfunds.services.business.merchant.entity.daos.MerchantDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public MerchantDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

    @Override
    protected IbatisBaseStatement getIbatisBaseStatement() {
        if (ibatisBaseStatement == null) {
            ibatisBaseStatement = new IbatisBaseStatement();
            ibatisBaseStatement.setInsertStatementId("com.dyb.platforms.fixfunds.services.business.merchant.dao.IMerchantDao.insertObject");
            ibatisBaseStatement.setUpdateStatementId("com.dyb.platforms.fixfunds.services.business.merchant.dao.IMerchantDao.updateObject");
            ibatisBaseStatement.setDeleteStatementId("com.dyb.platforms.fixfunds.services.business.merchant.dao.IMerchantDao.deleteObject");
            ibatisBaseStatement.setGetHasDetailStatementId("com.dyb.platforms.fixfunds.services.business.merchant.dao.IMerchantDao.getDetailObject");
            ibatisBaseStatement.setGetNoDetailStatementId("com.dyb.platforms.fixfunds.services.business.merchant.dao.IMerchantDao.getBaseObject");
            ibatisBaseStatement.setWhereDeleteStatementId("com.dyb.platforms.fixfunds.services.business.merchant.dao.IMerchantDao.deleteObjectByWhere");
            ibatisBaseStatement.setQueryCountStatementId("com.dyb.platforms.fixfunds.services.business.merchant.dao.IMerchantDao.queryCount");
            ibatisBaseStatement.setQueryHasDetailListStatementId("com.dyb.platforms.fixfunds.services.business.merchant.dao.IMerchantDao.queryDetailList");
            ibatisBaseStatement.setQueryNoDetailListStatementId("com.dyb.platforms.fixfunds.services.business.merchant.dao.IMerchantDao.queryBaseList");
        }
        return ibatisBaseStatement;
    }

}
