/**
 * 2016/10/10 10:24:00 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.accountincentive.entity;

import com.dyb.platforms.fixfunds.services.business.account.entity.em.AccountType;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 账户激励
 * Created by lenovo on 2016/10/10.
 */
public class AccountIncentive implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -3540430033365464576L;

    // 账户激励code [主键]
    private String accountIncentiveCode;
    @JsonFormat(pattern = "yyyy-MM-dd", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    // 激励日期
    private Date accountIncentiveTime;
    // 爱心数量
    private Double loveNum;
    // 爱心单价
    private Double lovePrice;
    // 激励信使豆
    private Double messengerBean;
    // 消费来源
    private AccountType source;
    // 账户code
    private String accountCode;
    // 激励模式
    private Integer incentiveMode;

    /** 
     * 获取账户激励code [主键]
     * 
     * @return 账户激励code
     */
    public String getAccountIncentiveCode() {
        return accountIncentiveCode;
    }

    /** 
     * 设置账户激励code [主键]
     * 
     * @param accountIncentiveCode 账户激励code
     */
    public void setAccountIncentiveCode(String accountIncentiveCode) {
        this.accountIncentiveCode = accountIncentiveCode;
    }

    /** 
     * 获取激励日期
     * 
     * @return 激励日期
     */
    public Date getAccountIncentiveTime() {
        return accountIncentiveTime;
    }

    /** 
     * 设置激励日期
     * 
     * @param accountIncentiveTime 激励日期
     */
    public void setAccountIncentiveTime(Date accountIncentiveTime) {
        this.accountIncentiveTime = accountIncentiveTime;
    }

    /** 
     * 获取爱心数量
     * 
     * @return 爱心数量
     */
    public Double getLoveNum() {
        return loveNum;
    }

    /** 
     * 设置爱心数量
     * 
     * @param loveNum 爱心数量
     */
    public void setLoveNum(Double loveNum) {
        this.loveNum = loveNum;
    }

    /** 
     * 获取爱心单价
     * 
     * @return 爱心单价
     */
    public Double getLovePrice() {
        return lovePrice;
    }

    /** 
     * 设置爱心单价
     * 
     * @param lovePrice 爱心单价
     */
    public void setLovePrice(Double lovePrice) {
        this.lovePrice = lovePrice;
    }

    /** 
     * 获取激励信使豆
     * 
     * @return 激励信使豆
     */
    public Double getMessengerBean() {
        return messengerBean;
    }

    /** 
     * 设置激励信使豆
     * 
     * @param messengerBean 激励信使豆
     */
    public void setMessengerBean(Double messengerBean) {
        this.messengerBean = messengerBean;
    }

    /** 
     * 获取消费来源
     * 
     * @return 消费来源
     */
    public AccountType getSource() {
        return source;
    }

    /** 
     * 设置消费来源
     * 
     * @param source 消费来源
     */
    public void setSource(AccountType source) {
        this.source = source;
    }

    /** 
     * 获取账户code
     * 
     * @return 账户code
     */
    public String getAccountCode() {
        return accountCode;
    }

    /** 
     * 设置账户code
     * 
     * @param accountCode 账户code
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

    /** 
     * 获取激励模式
     * 
     * @return 激励模式
     */
    public Integer getIncentiveMode() {
        return incentiveMode;
    }

    /** 
     * 设置激励模式
     * 
     * @param incentiveMode 激励模式
     */
    public void setIncentiveMode(Integer incentiveMode) {
        this.incentiveMode = incentiveMode;
    }

}
