/**
 * 2016/3/1 15:53:44 Administrator created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.businessprocess.dao;


import com.dyb.platforms.fixfunds.services.business.businessprocess.entity.BusinessPaper;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 业务单头模块 Ibatis Dao 接口
 * Created by Administrator on 2016/03/01.
 */
public interface IBusinessPaperDao extends IIbatisDataDAO<BusinessPaper, String> {

}
