/**
 * 2016/10/10 10:43:46 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.donation.dao;

import com.dyb.platforms.fixfunds.services.business.donation.entity.Donation;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 直捐 Ibatis Dao 接口
 * Created by lenovo on 2016/10/10.
 */
public interface IDonationDao extends IIbatisDataDAO<Donation, String> {

}
