/**
 * 2016/10/20 16:45:47 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.salesman.dao;

import com.dyb.platforms.fixfunds.services.business.salesman.entity.Salesman;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 业务员信息 Ibatis Dao 接口
 * Created by lenovo on 2016/10/20.
 */
public interface ISalesmanDao extends IIbatisDataDAO<Salesman, String> {

}
