/**
 * 2016/9/20 14:48:04 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.recommended.dao;

import com.dyb.platforms.fixfunds.services.business.recommended.entity.Recommended;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 推荐信息表 Ibatis Dao 接口
 * Created by lenovo on 2016/09/20.
 */
public interface IRecommendedDao extends IIbatisDataDAO<Recommended, String> {

}
