/**
 * 2016/9/20 14:48:04 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.recommended.entity;

import com.dyb.platforms.fixfunds.services.business.recommended.entity.em.AccountType;

/**
 * 推荐信息表
 * Created by lenovo on 2016/09/20.
 */
public class Recommended implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -5508656294787608576L;

    // 推荐编号code [主键]
    private String recommendedCode;
    // 推荐人code
    private String referrerCode;
    // 推荐人类型
    private AccountType referrerType;
    // 被推荐人code
    private String btjrCode;
    // 被推荐人类型
    private AccountType btjrType;
    // 激励信使豆
    private Double incentiveMessengerBean;

    /** 
     * 获取推荐编号code [主键]
     * 
     * @return 推荐编号code
     */
    public String getRecommendedCode() {
        return recommendedCode;
    }

    /** 
     * 设置推荐编号code [主键]
     * 
     * @param recommendedCode 推荐编号code
     */
    public void setRecommendedCode(String recommendedCode) {
        this.recommendedCode = recommendedCode;
    }

    /** 
     * 获取推荐人code
     * 
     * @return 推荐人code
     */
    public String getReferrerCode() {
        return referrerCode;
    }

    /** 
     * 设置推荐人code
     * 
     * @param referrerCode 推荐人code
     */
    public void setReferrerCode(String referrerCode) {
        this.referrerCode = referrerCode;
    }

    /** 
     * 获取推荐人类型
     * 
     * @return 推荐人类型
     */
    public AccountType getReferrerType() {
        return referrerType;
    }

    /** 
     * 设置推荐人类型
     * 
     * @param referrerType 推荐人类型
     */
    public void setReferrerType(AccountType referrerType) {
        this.referrerType = referrerType;
    }

    /** 
     * 获取被推荐人code
     * 
     * @return 被推荐人code
     */
    public String getBtjrCode() {
        return btjrCode;
    }

    /** 
     * 设置被推荐人code
     * 
     * @param btjrCode 被推荐人code
     */
    public void setBtjrCode(String btjrCode) {
        this.btjrCode = btjrCode;
    }

    /** 
     * 获取被推荐人类型
     * 
     * @return 被推荐人类型
     */
    public AccountType getBtjrType() {
        return btjrType;
    }

    /** 
     * 设置被推荐人类型
     * 
     * @param btjrType 被推荐人类型
     */
    public void setBtjrType(AccountType btjrType) {
        this.btjrType = btjrType;
    }

    /** 
     * 获取激励信使豆
     * 
     * @return 激励信使豆
     */
    public Double getIncentiveMessengerBean() {
        return incentiveMessengerBean;
    }

    /** 
     * 设置激励信使豆
     * 
     * @param incentiveMessengerBean 激励信使豆
     */
    public void setIncentiveMessengerBean(Double incentiveMessengerBean) {
        this.incentiveMessengerBean = incentiveMessengerBean;
    }

}
