/**
 * 2016/9/11 15:57:29 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.user.dao;

import com.dyb.platforms.fixfunds.services.business.user.entity.Permissions;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 权限信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/11.
 */
public interface IPermissionsDao extends IIbatisDataDAO<Permissions, String> {

}
