/**
 * 2016/9/11 11:07:35 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.user.dao;

import com.dyb.platforms.fixfunds.services.business.user.entity.User;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 用户信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/11.
 */
public interface IUserDao extends IIbatisDataDAO<User, String> {

}
