/**
 * 2016/3/1 15:53:44 Administrator created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.user.dao;


import com.dyb.platforms.fixfunds.services.business.user.entity.User;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 用户模块 Ibatis Dao 接口
 * Created by Administrator on 2016/03/01.
 */
public interface IUserDao extends IIbatisDataDAO<User, String> {

}
