/**
 * 2016/9/11 11:07:35 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.user.dao;

import com.dyb.platforms.fixfunds.services.business.user.entity.User;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IbatisBaseStatement;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IbatisDataDAOImpl;
import org.apache.ibatis.session.SqlSession;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 用户信息 Ibatis Dao 实现
 * Created by lenovo on 2016/09/11.
 */
@Repository
public class UserDao extends IbatisDataDAOImpl<User, String> implements IUserDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="userDao" class="com.dyb.platforms.fixfunds.services.business.user.entity.daos.UserDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    public UserDao(SqlSession sqlSession) {
        super(sqlSession);
    }

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public UserDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

    @Override
    protected IbatisBaseStatement getIbatisBaseStatement() {
        if (ibatisBaseStatement == null) {
            ibatisBaseStatement = new IbatisBaseStatement();
            ibatisBaseStatement.setInsertStatementId("com.dyb.platforms.fixfunds.services.business.user.dao.IUserDao.insertObject");
            ibatisBaseStatement.setUpdateStatementId("com.dyb.platforms.fixfunds.services.business.user.dao.IUserDao.updateObject");
            ibatisBaseStatement.setDeleteStatementId("com.dyb.platforms.fixfunds.services.business.user.dao.IUserDao.deleteObject");
            ibatisBaseStatement.setGetHasDetailStatementId("com.dyb.platforms.fixfunds.services.business.user.dao.IUserDao.getDetailObject");
            ibatisBaseStatement.setGetNoDetailStatementId("com.dyb.platforms.fixfunds.services.business.user.dao.IUserDao.getBaseObject");
            ibatisBaseStatement.setWhereDeleteStatementId("com.dyb.platforms.fixfunds.services.business.user.dao.IUserDao.deleteObjectByWhere");
            ibatisBaseStatement.setQueryCountStatementId("com.dyb.platforms.fixfunds.services.business.user.dao.IUserDao.queryCount");
            ibatisBaseStatement.setQueryHasDetailListStatementId("com.dyb.platforms.fixfunds.services.business.user.dao.IUserDao.queryDetailList");
            ibatisBaseStatement.setQueryNoDetailListStatementId("com.dyb.platforms.fixfunds.services.business.user.dao.IUserDao.queryBaseList");
        }
        return ibatisBaseStatement;
    }

}
