/**
 * 2016/10/8 15:36:19 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.blacklist.dao;

import com.dyb.platforms.fixfunds.services.business.blacklist.entity.Blacklist;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 黑名单 Ibatis Dao 接口
 * Created by lenovo on 2016/10/08.
 */
public interface IBlacklistDao extends IIbatisDataDAO<Blacklist, String> {

}
