/**
 * 2016/10/10 10:40:33 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.conversion.dao;

import com.dyb.platforms.fixfunds.services.business.conversion.entity.Conversion;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 转换信使豆记录 Ibatis Dao 接口
 * Created by lenovo on 2016/10/10.
 */
public interface IConversionDao extends IIbatisDataDAO<Conversion, String> {

}
