/**
 * 2016/9/27 20:18:11 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.sendaddress.entity;

import java.util.Date;

/**
 * 寄送地址
 * Created by lenovo on 2016/09/27.
 */
public class SendAddress implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -235274974366312352L;

    // 寄送地址code [主键]
    private String sendAddressCode;
    // 收件人
    private String receiver;
    // 省份
    private String province;
    // 市区
    private String city;
    // 详细地址
    private String address;
    // 邮政编码
    private String postalcode;
    // 电话号码
    private String phone;
    // 默认选择
    private Boolean defaultChecked;
    // 创建时间
    private Date createTime;
    // 账户code
    private String accountCode;

    /**
     * 获取寄送地址code [主键]
     *
     * @return 寄送地址code
     */
    public String getSendAddressCode() {
        return sendAddressCode;
    }

    /**
     * 设置寄送地址code [主键]
     *
     * @param sendAddressCode 寄送地址code
     */
    public void setSendAddressCode(String sendAddressCode) {
        this.sendAddressCode = sendAddressCode;
    }

    /**
     * 获取收件人
     *
     * @return 收件人
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * 设置收件人
     *
     * @param receiver 收件人
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * 获取省份
     *
     * @return 省份
     */
    public String getProvince() {
        return province;
    }

    /**
     * 设置省份
     *
     * @param province 省份
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * 获取市区
     *
     * @return 市区
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置市区
     *
     * @param city 市区
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * 获取详细地址
     *
     * @return 详细地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * 设置详细地址
     *
     * @param address 详细地址
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * 获取邮政编码
     *
     * @return 邮政编码
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * 设置邮政编码
     *
     * @param postalcode 邮政编码
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode;
    }

    /**
     * 获取电话号码
     *
     * @return 电话号码
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置电话号码
     *
     * @param phone 电话号码
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * 获取默认选择
     *
     * @return 默认选择
     */
    public Boolean isDefaultChecked() {
        return defaultChecked;
    }

    /**
     * 设置默认选择
     *
     * @param defaultChecked 默认选择
     */
    public void setDefaultChecked(Boolean defaultChecked) {
        this.defaultChecked = defaultChecked;
    }

    /**
     * 获取创建时间
     *
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置创建时间
     *
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取账户code
     *
     * @return 账户code
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * 设置账户code
     *
     * @param accountCode 账户code
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

}
