/**
 * 2016/10/10 10:33:57 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.invoiceapply.entity;

import com.dyb.platforms.fixfunds.services.business.invoiceapply.entity.em.InvoiceApplyStatus;
import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 让利款发票申请
 * Created by lenovo on 2016/10/10.
 */
public class InvoiceApply implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -8206036825760284672L;

    // 让利款发票申请编号code [主键]
    private String invoiceApplyCode;
    // 发票计算年月
    private String invoiceTime;
    // 营业总额
    private Double turnoverPrice;
    // 已交让利款
    private Double yetBenefitPrice;
    // 申请发票
    private Double applyInvoiceMoney;
    // 已开发票
    private Double yetInvoiceMoney;
    // 快递费
    private Double poundage;
    // 状态
    private InvoiceApplyStatus invoiceApplyStatus;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    // 申请时间
    private Date applyTime;
    // 商家账户code
    private String accountCode;
    //纳税人识别号
    private String taxpayers;
    // 开户行
    private String bankName;
    // 开户支行
    private String bankBranch;
    // 卡号
    private String bankNum;
    // 开户名称
    private String bankAccountName;

    /** 
     * 获取让利款发票申请编号code [主键]
     * 
     * @return 让利款发票申请编号code
     */
    public String getInvoiceApplyCode() {
        return invoiceApplyCode;
    }

    /** 
     * 设置让利款发票申请编号code [主键]
     * 
     * @param invoiceApplyCode 让利款发票申请编号code
     */
    public void setInvoiceApplyCode(String invoiceApplyCode) {
        this.invoiceApplyCode = invoiceApplyCode;
    }

    /** 
     * 获取发票计算年月
     * 
     * @return 发票计算年月
     */
    public String getInvoiceTime() {
        return invoiceTime;
    }

    /** 
     * 设置发票计算年月
     * 
     * @param invoiceTime 发票计算年月
     */
    public void setInvoiceTime(String invoiceTime) {
        this.invoiceTime = invoiceTime;
    }

    /** 
     * 获取营业总额
     * 
     * @return 营业总额
     */
    public Double getTurnoverPrice() {
        return turnoverPrice;
    }

    /** 
     * 设置营业总额
     * 
     * @param turnoverPrice 营业总额
     */
    public void setTurnoverPrice(Double turnoverPrice) {
        this.turnoverPrice = turnoverPrice;
    }

    /** 
     * 获取已交让利款
     * 
     * @return 已交让利款
     */
    public Double getYetBenefitPrice() {
        return yetBenefitPrice;
    }

    /** 
     * 设置已交让利款
     * 
     * @param yetBenefitPrice 已交让利款
     */
    public void setYetBenefitPrice(Double yetBenefitPrice) {
        this.yetBenefitPrice = yetBenefitPrice;
    }

    /** 
     * 获取申请发票
     * 
     * @return 申请发票
     */
    public Double getApplyInvoiceMoney() {
        return applyInvoiceMoney;
    }

    /** 
     * 设置申请发票
     * 
     * @param applyInvoiceMoney 申请发票
     */
    public void setApplyInvoiceMoney(Double applyInvoiceMoney) {
        this.applyInvoiceMoney = applyInvoiceMoney;
    }

    /** 
     * 获取已开发票
     * 
     * @return 已开发票
     */
    public Double getYetInvoiceMoney() {
        return yetInvoiceMoney;
    }

    /** 
     * 设置已开发票
     * 
     * @param yetInvoiceMoney 已开发票
     */
    public void setYetInvoiceMoney(Double yetInvoiceMoney) {
        this.yetInvoiceMoney = yetInvoiceMoney;
    }

    /** 
     * 获取快递费
     * 
     * @return 快递费
     */
    public Double getPoundage() {
        return poundage;
    }

    /** 
     * 设置快递费
     * 
     * @param poundage 快递费
     */
    public void setPoundage(Double poundage) {
        this.poundage = poundage;
    }

    /** 
     * 获取状态
     * 
     * @return 状态
     */
    public InvoiceApplyStatus getInvoiceApplyStatus() {
        return invoiceApplyStatus;
    }

    /** 
     * 设置状态
     * 
     * @param invoiceApplyStatus 状态
     */
    public void setInvoiceApplyStatus(InvoiceApplyStatus invoiceApplyStatus) {
        this.invoiceApplyStatus = invoiceApplyStatus;
    }

    /** 
     * 获取申请时间
     * 
     * @return 申请时间
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /** 
     * 设置申请时间
     * 
     * @param applyTime 申请时间
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /** 
     * 获取商家账户code
     * 
     * @return 商家账户code
     */
    public String getAccountCode() {
        return accountCode;
    }

    /** 
     * 设置商家账户code
     * 
     * @param accountCode 商家账户code
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

    /**
     * 获取纳税人识别号
     *
     * @return 纳税人识别号
     */
    public String getTaxpayers() {
        return taxpayers;
    }

    /**
     * 设置纳税人识别号
     *
     * @param taxpayers 纳税人识别号
     */
    public void setTaxpayers(String taxpayers) {
        this.taxpayers = taxpayers;
    }

    /**
     * 获取开户行
     *
     * @return 开户行
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * 设置开户行
     *
     * @param bankName 开户行
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * 获取开户支行
     *
     * @return 开户支行
     */
    public String getBankBranch() {
        return bankBranch;
    }

    /**
     * 设置开户支行
     *
     * @param bankBranch 开户支行
     */
    public void setBankBranch(String bankBranch) {
        this.bankBranch = bankBranch;
    }

    /**
     * 获取卡号
     *
     * @return 卡号
     */
    public String getBankNum() {
        return bankNum;
    }

    /**
     * 设置卡号
     *
     * @param bankNum 卡号
     */
    public void setBankNum(String bankNum) {
        this.bankNum = bankNum;
    }

    /**
     * 获取开户名称
     *
     * @return 开户名称
     */
    public String getBankAccountName() {
        return bankAccountName;
    }

    /**
     * 设置开户名称
     *
     * @param bankAccountName 开户名称
     */
    public void setBankAccountName(String bankAccountName) {
        this.bankAccountName = bankAccountName;
    }
}
