/**
 * 2016/10/10 10:32:35 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.withdrawal.dao;

import com.dyb.platforms.fixfunds.services.business.withdrawal.entity.Withdrawal;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 回购记录 Ibatis Dao 接口
 * Created by lenovo on 2016/10/10.
 */
public interface IWithdrawalDao extends IIbatisDataDAO<Withdrawal, String> {

}
