/**
 * 2016/10/10 10:24:00 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.accountincentive.dao;

import com.dyb.platforms.fixfunds.services.business.accountincentive.entity.AccountIncentive;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 账户激励 Ibatis Dao 接口
 * Created by lenovo on 2016/10/10.
 */
public interface IAccountIncentiveDao extends IIbatisDataDAO<AccountIncentive, String> {

}
