/**
 * 2016/10/10 10:31:05 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.entity 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.transfer.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

/**
 * 转赠
 * Created by lenovo on 2016/10/10.
 */
public class Transfer implements java.io.Serializable {

    // 序列化版本
    private static final long serialVersionUID = -6698651247051847680L;

    // 转赠编号code [主键]
    private String transferCode;
    // 转赠人
    private String transferAccount;
    // 获赠人
    private String gainAccount;
    // 转赠日期
    private Date transferTime;
    // 信使豆
    private Double messengerBean;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", locale = "zh" , timezone="GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    // 创建时间
    private Date createTime;

    /** 
     * 获取转赠编号code [主键]
     * 
     * @return 转赠编号code
     */
    public String getTransferCode() {
        return transferCode;
    }

    /** 
     * 设置转赠编号code [主键]
     * 
     * @param transferCode 转赠编号code
     */
    public void setTransferCode(String transferCode) {
        this.transferCode = transferCode;
    }

    /** 
     * 获取转赠人
     * 
     * @return 转赠人
     */
    public String getTransferAccount() {
        return transferAccount;
    }

    /** 
     * 设置转赠人
     * 
     * @param transferAccount 转赠人
     */
    public void setTransferAccount(String transferAccount) {
        this.transferAccount = transferAccount;
    }

    /** 
     * 获取获赠人
     * 
     * @return 获赠人
     */
    public String getGainAccount() {
        return gainAccount;
    }

    /** 
     * 设置获赠人
     * 
     * @param gainAccount 获赠人
     */
    public void setGainAccount(String gainAccount) {
        this.gainAccount = gainAccount;
    }

    /** 
     * 获取转赠日期
     * 
     * @return 转赠日期
     */
    public Date getTransferTime() {
        return transferTime;
    }

    /** 
     * 设置转赠日期
     * 
     * @param transferTime 转赠日期
     */
    public void setTransferTime(Date transferTime) {
        this.transferTime = transferTime;
    }

    /** 
     * 获取信使豆
     * 
     * @return 信使豆
     */
    public Double getMessengerBean() {
        return messengerBean;
    }

    /** 
     * 设置信使豆
     * 
     * @param messengerBean 信使豆
     */
    public void setMessengerBean(Double messengerBean) {
        this.messengerBean = messengerBean;
    }

    /** 
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /** 
     * 设置创建时间
     * 
     * @param createTime 创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
