/**
 * 2016/10/14 17:20:42 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_imp 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.benefitdonation.dao;

import com.dyb.platforms.fixfunds.services.business.benefitdonation.entity.BenefitDonation;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IbatisBaseStatement;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IbatisDataDAOImpl;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

/**
 * 让利款捐赠 Ibatis Dao 实现
 * Created by lenovo on 2016/10/14.
 */
@Repository
public class BenefitDonationDao extends IbatisDataDAOImpl<BenefitDonation, String> implements IBenefitDonationDao {

    private IbatisBaseStatement ibatisBaseStatement;

    // dao的spring配置
    /*
    <bean id="benefitDonationDao" class="com.dyb.platforms.fixfunds.services.business.benefitdonation.entity.daos.BenefitDonationDao">
        <constructor-arg name="sqlSession" ref="sqlSession"/>
    </bean>
    */

    /**
     * 用Ibatis会话创建Dao
     * @param sqlSession Ibatis会话
     */
    @Autowired
    public BenefitDonationDao(SqlSessionTemplate sqlSession){
        super(sqlSession);
    }

	@Override
	protected IbatisBaseStatement getIbatisBaseStatement() {
		if (ibatisBaseStatement == null) {
			ibatisBaseStatement = new IbatisBaseStatement();
			ibatisBaseStatement.setInsertStatementId("com.dyb.platforms.fixfunds.services.business.benefitdonation.dao.IBenefitDonationDao.insertObject");
			ibatisBaseStatement.setUpdateStatementId("com.dyb.platforms.fixfunds.services.business.benefitdonation.dao.IBenefitDonationDao.updateObject");
			ibatisBaseStatement.setDeleteStatementId("com.dyb.platforms.fixfunds.services.business.benefitdonation.dao.IBenefitDonationDao.deleteObject");
			ibatisBaseStatement.setGetHasDetailStatementId("com.dyb.platforms.fixfunds.services.business.benefitdonation.dao.IBenefitDonationDao.getDetailObject");
			ibatisBaseStatement.setGetNoDetailStatementId("com.dyb.platforms.fixfunds.services.business.benefitdonation.dao.IBenefitDonationDao.getBaseObject");
			ibatisBaseStatement.setWhereDeleteStatementId("com.dyb.platforms.fixfunds.services.business.benefitdonation.dao.IBenefitDonationDao.deleteObjectByWhere");
			ibatisBaseStatement.setQueryCountStatementId("com.dyb.platforms.fixfunds.services.business.benefitdonation.dao.IBenefitDonationDao.queryCount");
			ibatisBaseStatement.setQueryHasDetailListStatementId("com.dyb.platforms.fixfunds.services.business.benefitdonation.dao.IBenefitDonationDao.queryDetailList");
			ibatisBaseStatement.setQueryNoDetailListStatementId("com.dyb.platforms.fixfunds.services.business.benefitdonation.dao.IBenefitDonationDao.queryBaseList");
		}
		return ibatisBaseStatement;
	}

}
