/**
 * 2016/10/14 17:20:42 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.benefitdonation.dao;

import com.dyb.platforms.fixfunds.services.business.benefitdonation.entity.BenefitDonation;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 让利款捐赠 Ibatis Dao 接口
 * Created by lenovo on 2016/10/14.
 */
public interface IBenefitDonationDao extends IIbatisDataDAO<BenefitDonation, String> {

}
