/**
 * 2016/10/10 10:35:19 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.recommendincentive.dao;

import com.dyb.platforms.fixfunds.services.business.recommendincentive.entity.RecommendIncentive;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 推荐激励信息 Ibatis Dao 接口
 * Created by lenovo on 2016/10/10.
 */
public interface IRecommendIncentiveDao extends IIbatisDataDAO<RecommendIncentive, String> {

}
