/**
 * 2016/9/20 13:52:45 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.member.dao;

import com.dyb.platforms.fixfunds.services.business.member.entity.Member;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 信使信息 Ibatis Dao 接口
 * Created by lenovo on 2016/09/20.
 */
public interface IMemberDao extends IIbatisDataDAO<Member, String> {

}
