/**
 * 2016/9/14 13:10:59 lenovo created.
 * Generated by Caven.CodeBuilder (funiJava.mybatis_dao_inf 1.0).
 */

package com.dyb.platforms.fixfunds.services.business.systemlog.dao;

import com.dyb.platforms.fixfunds.services.business.systemlog.entity.UserLog;
import com.dyb.platforms.fixfunds.services.utils.core.dao.IIbatisDataDAO;

/**
 * 用户操作日志 Ibatis Dao 接口
 * Created by lenovo on 2016/09/14.
 */
public interface IUserLogDao extends IIbatisDataDAO<UserLog, String> {

}
